import { crmFeatures, nav, platformLogos, trustItems, workbenchFeatures } from './data.js';

const page = document.body.dataset.page;
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function icon(name) { return `<span class="glyph" aria-hidden="true">${name}</span>`; }
function header() {
  return `<header class="site-header"><a class="brand" href="/"><img src="/brand/yike-logo.png" alt=""/><span>意客 <b>AI</b><small>INTELLIGENCE WORKSPACE</small></span></a><nav>${nav.map((item) => `<a href="${item.href}" class="${location.pathname === item.href ? 'active' : ''}">${item.label}</a>`).join('')}</nav><a class="header-cta" href="/contact/">预约演示 <span>↗</span></a><button class="menu-button" aria-label="打开菜单">☰</button></header>`;
}
function footer() {
  return `<footer><div class="footer-top"><a class="brand" href="/"><img src="/brand/yike-logo.png" alt=""/><span>意客 <b>AI</b><small>INTELLIGENCE WORKSPACE</small></span></a><p>把客户信号、销售动作与企业知识，组织成一套可以持续使用的工作系统。</p></div><div class="footer-grid"><div><h4>产品</h4><a href="/products/workbench/">商机工作台</a><a href="/products/crm/">客户情报 CRM</a><a href="/features/">能力全景</a></div><div><h4>开始使用</h4><a href="/download/">下载与试用</a><a href="/contact/">预约产品演示</a><a href="tel:15011569988">150 1156 9988</a></div><div><h4>关于意客</h4><a href="/roadmap/">产品路线</a><a href="/contact/">企业合作</a><a href="/">隐私与安全</a></div></div><div class="footer-bottom"><span>© 2026 意客 AI · Xinghe Technology</span><span>面向企业的客户情报与商机工作台</span></div></footer>`;
}
function layout(content, eyebrow = '意客 AI · 企业增长工作系统') { document.querySelector('#app').innerHTML = `${header()}<main>${content}</main>${footer()}`; }
function button(href, text, secondary = false) { return `<a class="button ${secondary ? 'button-secondary' : ''}" href="${href}">${text}<span>↗</span></a>`; }
function platformStrip() { return `<div class="platform-strip">${platformLogos.map(([name, short]) => `<span><i>${short}</i>${name}</span>`).join('')}<em>多平台连接 · 按授权与连接状态工作</em></div>`; }
function featureCards(items, accent = 'blue') { return `<div class="feature-grid ${accent}">${items.map((f) => `<article class="feature-card"><div class="feature-icon">${icon(f.icon)}</div><div><h3>${esc(f.title)}</h3><p>${esc(f.text)}</p>${f.tag ? `<span class="status-tag">${esc(f.tag)}</span>` : ''}</div></article>`).join('')}</div>`; }
function proofPanel() { return `<div class="proof-panel"><div class="proof-head"><span><i class="live-dot"></i> 工作台预览</span><span>实时证据视图</span></div><div class="proof-body"><div class="proof-sidebar"><b>意客 AI</b><span class="selected">商机工作台</span><span>业务画像</span><span>监控任务</span><span>触达中心</span><span>账号与授权</span></div><div class="proof-content"><div class="proof-title"><span>今日值得关注</span><small>基于已确认任务生成</small></div><div class="signal-card"><span class="signal-label">需求信号 · 公开来源</span><strong>正在寻找定制化 AI 解决方案</strong><p>来源：公开内容 · 2 小时前 · 证据已保存</p><div class="signal-foot"><b>高匹配</b><span>查看原文 ↗</span></div></div><div class="mini-row"><span>新增机会 <b>12</b></span><span>待复核 <b>04</b></span><span>待跟进 <b>07</b></span></div></div></div></div>`; }

function home() {
  layout(`<section class="hero"><div class="hero-glow"></div><div class="hero-copy"><span class="eyebrow">面向企业的 AI 客户情报与增长工作系统</span><h1>让每一次发现，<br/><span>更接近下一次成交。</span></h1><p class="hero-lead">意客 AI 把分散在公开平台、销售记录与企业知识里的信号，变成可核对、可协作、可执行的下一步。</p><div class="hero-actions">${button('/contact/', '预约产品演示')}${button('/download/', '下载与试用', true)}</div><div class="hero-note"><i class="live-dot"></i> 从真实业务场景开始，按阶段接入和验收</div></div><div class="hero-proof">${proofPanel()}</div></section><section class="brand-rail"><span>为销售团队建立一条持续运行的情报链</span><div>${['AI 业务画像', '多平台信号', '证据化机会', '人工确认触达', '持续跟进'].map((x, i) => `<b><i>0${i + 1}</i>${x}</b>`).join('')}</div></section><section class="section intro"><span class="eyebrow">两套产品，一条增长主线</span><h2>从找到机会，<br/>到把关系经营下去。</h2><p class="section-lead">意客 AI 商机工作台负责发现和推进，客户情报 CRM 负责沉淀和协作。可以独立使用，也可以围绕同一套销售流程组合交付。</p><div class="product-pair"><article class="product-card primary"><div class="product-card-top"><span class="product-kicker">PRODUCT 01 · DISCOVER</span><span class="product-mark">✦</span></div><h3>商机工作台</h3><p>找到正在发生的需求，保留证据，生成自然的下一步。</p><div class="product-list"><span>AI 业务画像与搜索条件</span><span>小红书 · 抖音 · B站 · 知乎</span><span>监控、复核、短句与跟进</span></div>${button('/products/workbench/', '了解商机工作台', true)}</article><article class="product-card secondary"><div class="product-card-top"><span class="product-kicker">PRODUCT 02 · OPERATE</span><span class="product-mark">◈</span></div><h3>客户情报 CRM</h3><p>把客户、活动、商机和情报，整理成团队可以长期使用的工作台。</p><div class="product-list"><span>线索、联系人、销售管道</span><span>客户情报证据账本</span><span>AI 研究、草稿与销售协作</span></div>${button('/products/crm/', '了解客户情报 CRM', true)}</article></div></section><section class="section dark-section"><div><span class="eyebrow">为什么是现在</span><h2>销售正在进入<br/><em>证据驱动的时代。</em></h2><p class="section-lead">客户的需求不会只出现在一个表单里。它藏在一条内容、一句评论、一次产品比较和一次团队讨论中。意客 AI 让这些变化被发现、理解并留下来。</p>${button('/features/', '查看能力全景')}</div><div class="trust-list">${trustItems.map(([title, text], i) => `<div class="trust-item"><span>0${i + 1}</span><div><strong>${title}</strong><p>${text}</p></div></div>`).join('')}</div></section><section class="section platform-section"><div class="section-heading"><div><span class="eyebrow">连接真实的客户声音</span><h2>一个工作台，<br/>看见更多需求发生。</h2></div><p>平台能力按连接授权和版本开放，研究结果保留原始来源和判断依据，团队可以从同一处开始行动。</p></div>${platformStrip()}<div class="screenshot-frame"><img src="/product-screenshots/workbench-navigation.png" alt="意客 AI 商机工作台界面"/><div class="screenshot-caption">界面示意 · 商机工作台的任务、平台连接与证据导航</div></div></section><section class="cta-section"><span class="eyebrow">把你的真实业务带进来</span><h2>先看一条完整链路，<br/>再决定从哪里开始。</h2><p>留下手机号，我们会围绕你的行业、客户和销售流程安排一次产品演示。</p>${button('/contact/', '预约 1 对 1 演示')}</section>`);
}

function productPage(kind) {
  const isCrm = kind === 'crm'; const title = isCrm ? '客户情报 CRM' : '商机工作台'; const lead = isCrm ? '让每一次销售跟进，都有下一步。' : '找到正在发生的需求，把机会推进到下一步。'; const body = isCrm ? '面向中国 B2B 销售团队的客户情报与跟进工作台。把公司、联系人、商机、活动、情报与 AI 草稿组织在一套可追溯的销售流程里。' : '面向各行业企业的 AI 商机发现与跟进工作台。把业务画像、多平台信号、原文证据和人工确认的触达动作连接起来。'; const features = isCrm ? crmFeatures : workbenchFeatures;
  layout(`<section class="product-hero ${isCrm ? 'crm-hero' : ''}"><div><span class="eyebrow">PRODUCT 0${isCrm ? '2' : '1'} · ${isCrm ? 'OPERATE' : 'DISCOVER'}</span><h1>${title}<br/><em>${lead}</em></h1><p class="hero-lead">${body}</p><div class="hero-actions">${button('/contact/', '预约演示')}${button('/download/', '下载与试用', true)}</div></div><div class="product-orbit">${isCrm ? '<div class="orbit-card"><span>本月销售概览</span><strong>¥ 1,280,000</strong><small>预计成交 · 基于已录入管道</small><div class="bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="orbit-chip">AI 客户情报 <b>●</b></div><div class="orbit-chip lower">下一步 · 7 条</div>' : proofPanel()}</div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">能力模块</span><h2>${isCrm ? '让销售团队，<br/>围绕同一份事实工作。' : '从业务理解，<br/>到下一步行动。'}</h2></div><p>${isCrm ? '不是把更多表格搬进系统，而是让客户状态、销售动作和情报证据彼此关联。' : '不是生成更多泛泛的名单，而是把值得判断的机会交给人，把判断所需的证据一起带上。'}</p></div>${featureCards(features, isCrm ? 'purple' : 'blue')}</section><section class="section product-showcase"><div class="showcase-copy"><span class="eyebrow">产品工作流</span><h2>${isCrm ? '从线索进入，<br/>到客户持续经营。' : '一条线索，<br/>完整走完发现到跟进。'}</h2><div class="workflow">${(isCrm ? ['导入或捕获线索', '补齐客户与联系人', 'AI 研究与情报复核', '销售活动与待办', '商机推进与复盘'] : ['确认业务画像', '生成并修改搜索条件', '多平台研究与原文读取', '人工复核机会证据', '复制草稿并记录反馈']).map((x, i) => `<div><i>0${i + 1}</i><span>${x}</span></div>`).join('')}</div></div><div class="showcase-media"><img src="/product-screenshots/${isCrm ? 'workbench-evidence.png' : 'workbench-task.png'}" alt="${title}产品界面示意"/><small>产品界面示意 · 实际可用模块以版本与连接状态为准</small></div></section><section class="section light-band"><span class="eyebrow">面向长期使用</span><h2>${isCrm ? '客户数据越完整，<br/>团队越容易协同。' : '越接近真实业务，<br/>越需要可追溯。'}</h2><div class="number-grid"><div><strong>可核对</strong><span>原文、来源、时间、证据链</span></div><div><strong>可协作</strong><span>角色、复核、待办、跟进记录</span></div><div><strong>可扩展</strong><span>平台连接、行业策略、部署方式</span></div></div></section><section class="cta-section"><span class="eyebrow">下一步</span><h2>用你的真实业务，<br/>验证它能不能带来改变。</h2><p>拨打 150 1156 9988，或预约一次产品演示。</p>${button('/contact/', '预约产品演示')}</section>`);
}

function featuresPage() { layout(`<section class="page-hero"><span class="eyebrow">CAPABILITY MAP · 能力全景</span><h1>不是更多功能，<br/><em>是一条完整的增长链。</em></h1><p>从信息捕获到客户跟进，意客 AI 把每个关键动作放进可追溯、可协作、可持续演进的系统里。</p></section><section class="section capability-table"><div class="cap-row cap-head"><span>能力域</span><span>解决什么问题</span><span>产品归属</span><span>状态</span></div>${[['业务画像', '让系统理解你的产品、客户与销售边界', '商机工作台', '客户端已提供'], ['多平台获客', '从公开内容中发现需求信号和项目变化', '商机工作台', '按连接状态提供'], ['证据与复核', '让每个判断都能回到原文和来源', '商机工作台', '核心能力'], ['监控与变化', '持续关注方向、作者和需求变化', '商机工作台', '企业方案'], ['客户与商机', '把线索、联系人、管道、合同和回款关联起来', '客户情报 CRM', '网页产品'], ['AI 客户研究', '补齐背景信息，形成可复用的客户简报', '客户情报 CRM', '依赖外部服务'], ['触达与跟进', '确认后生成草稿，记录回复和下一步', '双产品协同', '按项目开通'], ['企业部署', '按数据边界、角色与环境要求交付', '双产品协同', '方案评估']].map((r) => `<div class="cap-row"><strong>${r[0]}</strong><span>${r[1]}</span><span>${r[2]}</span><b>${r[3]}</b></div>`).join('')}</div><section class="section"><div class="section-heading"><div><span class="eyebrow">AI 在哪里</span><h2>AI 负责理解和推进，<br/>人负责确认和决策。</h2></div><p>我们把 AI 放在业务流程里，而不是停在聊天窗口。它可以帮助生成、整理和解释，但关键的外部动作仍然由企业授权和人工确认控制。</p></div><div class="ai-layers"><div><i>01</i><h3>理解</h3><p>理解业务画像、客户语境和需求类型。</p></div><div><i>02</i><h3>研究</h3><p>围绕公开来源组织搜索、证据和变化。</p></div><div><i>03</i><h3>建议</h3><p>生成搜索条件、判断理由和建联短句。</p></div><div><i>04</i><h3>推进</h3><p>把确认后的动作和反馈写回工作流。</p></div></div></section><section class="cta-section"><span class="eyebrow">准备好开始了吗</span><h2>从一个具体的销售问题开始。</h2>${button('/contact/', '预约演示')}</section>`); }

function downloadPage() { layout(`<section class="page-hero"><span class="eyebrow">DOWNLOAD · 下载与试用</span><h1>先装上，<br/><em>再用真实业务判断。</em></h1><p>两个产品可以独立使用，也可以围绕同一套客户增长流程组合。下载包和在线体验入口会按版本、平台和授权状态提供。</p></section><section class="section download-grid"><article class="download-card featured"><span class="product-kicker">PRODUCT 01 · DESKTOP</span><h2>意客 AI 商机工作台</h2><p>桌面客户端，用于业务画像、平台连接、获客任务、机会复核与跟进。</p><div class="download-meta"><span>macOS · Apple Silicon</span><span>Windows · 申请体验</span></div><div class="download-actions"><a class="button" href="tel:15011569988">获取安装包 <span>↗</span></a><a href="/products/workbench/" class="text-link">查看功能</a></div><small>下载地址将按客户版本和授权方式发送，避免把未验收构建物直接用于生产。</small></article><article class="download-card"><span class="product-kicker">PRODUCT 02 · WEB APP</span><h2>意客 AI 客户情报 CRM</h2><p>网页产品，用于客户、联系人、销售管道、活动、情报与 AI 草稿协作。</p><div class="download-meta"><span>浏览器直接使用</span><span>私有化部署可评估</span></div><div class="download-actions"><a class="button button-secondary" href="/contact/">申请在线体验 <span>↗</span></a><a href="/products/crm/" class="text-link">查看功能</a></div><small>CRM 当前提供网页体验与部署申请，桌面客户端正在筹备。</small></article></section><section class="section install-steps"><span class="eyebrow">三步开始</span><h2>不用先理解所有功能。</h2><div class="steps"><div><b>01</b><h3>说明你的业务</h3><p>告诉我们卖什么、卖给谁、现在如何获客。</p></div><div><b>02</b><h3>拿到匹配版本</h3><p>按平台、部署方式和角色配置体验入口。</p></div><div><b>03</b><h3>用真实结果评估</h3><p>围绕一条业务链路看证据、效率和下一步。</p></div></div></section><section class="cta-section"><span class="eyebrow">需要安装包或试用码</span><h2>直接联系产品顾问。</h2><p>电话：150 1156 9988</p>${button('/contact/', '申请试用与演示')}</section>`); }

function roadmapPage() { layout(`<section class="page-hero"><span class="eyebrow">ROADMAP · 产品演进</span><h1>从一条链路开始，<br/><em>让系统越用越懂业务。</em></h1><p>产品会按真实客户反馈持续开放能力。路线图代表产品方向，不等同于当前版本已经开通。</p></section><section class="section roadmap"><div class="road-item current"><div><span>NOW · 当前可体验</span><h2>建立第一条证据链</h2><p>业务画像、搜索条件、公开来源研究、机会证据、人工复核、联系草稿与跟进记录。</p></div><i>01</i></div><div class="road-item next"><div><span>NEXT · 企业方案</span><h2>持续监控与协作</h2><p>多平台连接、监控计划、项目变化时间线、团队角色、客户情报与 CRM 协同。</p></div><i>02</i></div><div class="road-item future"><div><span>EVOLVE · 持续演进</span><h2>让系统越来越知道去哪里找</h2><p>来源效果沉淀、机会扩展、预算优化、跨来源关联和更贴合业务的 AI 建议。</p></div><i>03</i></div></section><section class="section light-band"><div class="section-heading"><div><span class="eyebrow">交付原则</span><h2>先说清楚范围，<br/>再用结果扩大范围。</h2></div><p>每个企业项目都会把版本、数据边界、连接状态、实施范围和验收方式写进方案，避免“看起来什么都有，实际无人负责”。</p></div>${featureCards([{icon:'✓',title:'版本清晰',text:'已提供、可开通、规划中分别说明。'},{icon:'⌁',title:'范围可验收',text:'按真实业务动作和结果定义交付。'},{icon:'◌',title:'持续可升级',text:'保留数据和流程，逐步增加平台与能力。'}])}</section><section class="cta-section"><span class="eyebrow">一起定义下一步</span><h2>告诉我们你现在最想解决的销售问题。</h2>${button('/contact/', '联系产品顾问')}</section>`); }

function contactPage() { layout(`<section class="contact-hero"><span class="eyebrow">CONTACT · 预约演示</span><h1>带着真实业务来，<br/><em>我们用系统现场回答。</em></h1><p>不需要准备复杂材料。告诉我们你的产品、客户和当前获客方式，我们会安排适合的产品演示与试用路径。</p><div class="contact-box"><div><span class="contact-label">产品顾问</span><strong>150 1156 9988</strong><p>电话或微信联系，说明“意客 AI 试用”。</p><a class="button" href="tel:15011569988">立即联系 <span>↗</span></a></div><div class="contact-divider"></div><div><span class="contact-label">演示会看到什么</span><ul><li>从业务画像生成一批搜索条件</li><li>从原文证据复核一条商机</li><li>查看客户情报与下一步跟进</li></ul></div></div></section><section class="section contact-note"><span class="eyebrow">给顾问的一句话</span><h2>“我们卖 ______，主要想找到 ______。”</h2><p>先从一句业务描述开始，剩下的交给我们一起拆解。</p></section>`); }

if (page === 'home') home(); else if (page === 'products-workbench') productPage('workbench'); else if (page === 'products-crm') productPage('crm'); else if (page === 'features') featuresPage(); else if (page === 'download') downloadPage(); else if (page === 'roadmap') roadmapPage(); else contactPage();

document.addEventListener('click', (event) => { const button = event.target.closest('.menu-button'); if (button) document.querySelector('nav')?.classList.toggle('open'); });
