import type { Opportunity, Profile } from "../../src/renderer/domain/models";
import type {
  ResearchBinding,
  ResearchCollection,
  ResearchRecord,
  ResearchTimeline,
  SimilarResearchPlan,
} from "../../src/renderer/domain/opportunityResearch";
export const researchRow: Opportunity = {
  id: "test-opportunity",
  title: "TEST 服务询价",
  buyer: "TEST 需求方",
  summary: "TEST 摘要",
  excerpt: "TEST 公开询价，资料截止为9月20日。",
  matchReason: "TEST 匹配理由",
  actionSignal: "TEST 询价",
  value: "TEST 待核验",
  risk: "TEST 实际预算未知",
  contactPath: "TEST 人工核验",
  url: "https://example.test/inquiry",
  platform: "公开网站",
  sourceStatus: "OPEN",
  profileStatus: "CONFIRMED",
  profileVersionId: "profile-v1",
  reviewer: "TEST 复核员",
  reviewedAt: "2026-09-09T12:00:00+08:00",
  publishedAt: "2026-09-08T10:00:00+08:00",
  updatedAt: "2026-09-09T12:00:00+08:00",
  intentStatus: "READY",
  comment: "",
  dm: "",
  sourceEvidenceVersion: "v2",
};
export const researchProfile: Profile = {
  id: "profile-v1",
  version: 1,
  status: "CONFIRMED",
  description: "TEST 已确认画像",
  fields: {
    service: "TEST 服务",
    customer: "TEST 客户",
    regions: "TEST 地域",
    preference: "",
    exclusions: "",
  },
};
export const binding: ResearchBinding = {
  userId: "test-user",
  accountScope: { id: "test-space", version: 1 },
  opportunityId: researchRow.id,
  profileVersionId: researchRow.profileVersionId,
  sourceUrl: researchRow.url,
  evidenceVersion: "v2",
};
export const researchRecord: ResearchRecord = {
  opportunity: researchRow,
  classification: {
    category: "OPPORTUNITY",
    type: "询价",
    reason: "TEST 原文明确征询报价",
    ruleVersion: "test-rule-v1",
    evidence: [
      {
        sourceUrl: researchRow.url,
        evidenceVersion: "v2",
        quote: "TEST 公开询价",
      },
    ],
    review: {
      status: "RECOGNIZED",
      reviewer: "TEST 复核员",
      reviewedAt: "2026-09-09T12:00:00+08:00",
    },
  },
};
export const collection: ResearchCollection = {
  schemaVersion: 1,
  userId: "test-user",
  accountScope: { id: "test-space", version: 1 },
  snapshotId: "test-list",
  generatedAt: new Date(Date.now() - 60_000).toISOString(),
  expiresAt: "2099-01-01T00:00:00Z",
  records: [researchRecord],
};
export const timeline: ResearchTimeline = {
  schemaVersion: 1,
  binding,
  snapshotId: "test-timeline",
  generatedAt: collection.generatedAt,
  expiresAt: collection.expiresAt,
  versions: [
    {
      id: "v1",
      ordinal: 1,
      previousVersionId: null,
      sourceUrl: researchRow.url,
      content: "TEST 公开询价，资料截止为9月15日。",
      publishedAt: researchRow.publishedAt,
      observedAt: null,
      access: "AVAILABLE",
    },
    {
      id: "v2",
      ordinal: 2,
      previousVersionId: "v1",
      sourceUrl: researchRow.url,
      content: researchRow.excerpt,
      publishedAt: null,
      observedAt: collection.generatedAt,
      access: "FAILED",
    },
  ],
  changes: [
    {
      id: "change-1",
      kind: "DEADLINE",
      label: "TEST 资料截止延后",
      from: {
        sourceUrl: researchRow.url,
        evidenceVersion: "v1",
        quote: "资料截止为9月15日",
      },
      to: {
        sourceUrl: researchRow.url,
        evidenceVersion: "v2",
        quote: "资料截止为9月20日",
      },
      occurredAt: null,
    },
  ],
  contacts: [
    {
      id: "manual-1",
      opportunityId: researchRow.id,
      kind: "MANUAL",
      label: "TEST 人工联系",
      detail: "TEST 人工填写内容，不是渠道回流",
      occurredAt: null,
      recordedAt: collection.generatedAt,
      operator: "TEST 操作人",
      receiptId: "",
    },
  ],
  gaps: ["TEST 实际采购预算"],
};
export const similar: SimilarResearchPlan = {
  schemaVersion: 1,
  requestId: "request",
  suggestionId: "test-suggestion",
  binding,
  generatedAt: collection.generatedAt,
  expiresAt: collection.expiresAt,
  eligible: true,
  ineligibleReason: "",
  recognition: {
    reviewer: "TEST 复核员",
    reviewedAt: researchRecord.classification.review.reviewedAt!,
    evidenceVersion: "v2",
  },
  rationale: "TEST 同类公开需求",
  evidence: researchRecord.classification.evidence,
  profileId: researchProfile.id,
  profileVersion: 1,
  keywords: ["TEST 服务询价", "TEST 服务比较"],
  exclusions: ["TEST 招聘"],
  supportedPlatforms: ["web"],
  originalScope: "TEST 原始服务范围",
  additionalScope: "TEST 新增同类询价方向",
  usage: { status: "UNKNOWN", reason: "TEST 未接计量" },
};
