import type { RadarPlan, RadarPlanInput } from "../../src/shared/radarPlan";

/** TEST synthetic inputs; plans generated by pilot.radar_plan_api.preview_plan.
 * No browser planner, external search, customer content, or production fallback.
 * Keep these exact snapshots in sync with the shared Python planner.
 */
export const RADAR_VISUAL_FIXTURES = [
  {
    "name": "industrial-pump",
    "input": {
      "querySeeds": [
        "工业水泵"
      ],
      "intentSignals": [],
      "exclusions": [
        "招聘",
        "二手"
      ],
      "region": "",
      "demandTypes": [
        "INQUIRY",
        "COMPARISON",
        "REPLACEMENT"
      ]
    },
    "plan": {
      "version": "radar-search-directions-v1",
      "strategies": [
        {
          "id": "quick",
          "name": "快速搜索",
          "purpose": "先查找直接表达需求的内容",
          "queries": [
            "工业水泵 询问方案、价格或寻找供应商"
          ]
        },
        {
          "id": "condition",
          "name": "条件核验",
          "purpose": "结合已确认条件减少无关结果",
          "queries": [
            "工业水泵 询问方案、价格或寻找供应商 -招聘 -二手",
            "工业水泵 比较方案或供应商并准备选型 -招聘 -二手",
            "工业水泵 替换现有供应商或系统 -招聘 -二手"
          ]
        },
        {
          "id": "broad",
          "name": "扩展搜索",
          "purpose": "用相关表达补查可能遗漏的需求",
          "queries": [
            "工业水泵"
          ]
        }
      ],
      "queries": [
        "工业水泵 询问方案、价格或寻找供应商",
        "工业水泵 询问方案、价格或寻找供应商 -招聘 -二手",
        "工业水泵",
        "工业水泵 比较方案或供应商并准备选型 -招聘 -二手",
        "工业水泵 替换现有供应商或系统 -招聘 -二手"
      ]
    }
  },
  {
    "name": "centrifugal-pump",
    "input": {
      "querySeeds": [
        "离心水泵"
      ],
      "intentSignals": [],
      "exclusions": [
        "招聘",
        "二手"
      ],
      "region": "",
      "demandTypes": [
        "INQUIRY",
        "COMPARISON",
        "REPLACEMENT"
      ]
    },
    "plan": {
      "version": "radar-search-directions-v1",
      "strategies": [
        {
          "id": "quick",
          "name": "快速搜索",
          "purpose": "先查找直接表达需求的内容",
          "queries": [
            "离心水泵 询问方案、价格或寻找供应商"
          ]
        },
        {
          "id": "condition",
          "name": "条件核验",
          "purpose": "结合已确认条件减少无关结果",
          "queries": [
            "离心水泵 询问方案、价格或寻找供应商 -招聘 -二手",
            "离心水泵 比较方案或供应商并准备选型 -招聘 -二手",
            "离心水泵 替换现有供应商或系统 -招聘 -二手"
          ]
        },
        {
          "id": "broad",
          "name": "扩展搜索",
          "purpose": "用相关表达补查可能遗漏的需求",
          "queries": [
            "离心水泵"
          ]
        }
      ],
      "queries": [
        "离心水泵 询问方案、价格或寻找供应商",
        "离心水泵 询问方案、价格或寻找供应商 -招聘 -二手",
        "离心水泵",
        "离心水泵 比较方案或供应商并准备选型 -招聘 -二手",
        "离心水泵 替换现有供应商或系统 -招聘 -二手"
      ]
    }
  },
  {
    "name": "both-pumps",
    "input": {
      "querySeeds": [
        "工业水泵",
        "离心水泵"
      ],
      "intentSignals": [],
      "exclusions": [
        "招聘",
        "二手"
      ],
      "region": "",
      "demandTypes": [
        "INQUIRY",
        "COMPARISON",
        "REPLACEMENT"
      ]
    },
    "plan": {
      "version": "radar-search-directions-v1",
      "strategies": [
        {
          "id": "quick",
          "name": "快速搜索",
          "purpose": "先查找直接表达需求的内容",
          "queries": [
            "工业水泵 询问方案、价格或寻找供应商",
            "离心水泵 询问方案、价格或寻找供应商"
          ]
        },
        {
          "id": "condition",
          "name": "条件核验",
          "purpose": "结合已确认条件减少无关结果",
          "queries": [
            "工业水泵 询问方案、价格或寻找供应商 -招聘 -二手",
            "离心水泵 询问方案、价格或寻找供应商 -招聘 -二手",
            "工业水泵 比较方案或供应商并准备选型 -招聘 -二手",
            "离心水泵 比较方案或供应商并准备选型 -招聘 -二手",
            "工业水泵 替换现有供应商或系统 -招聘 -二手",
            "离心水泵 替换现有供应商或系统 -招聘 -二手"
          ]
        },
        {
          "id": "broad",
          "name": "扩展搜索",
          "purpose": "用相关表达补查可能遗漏的需求",
          "queries": [
            "工业水泵",
            "离心水泵"
          ]
        }
      ],
      "queries": [
        "工业水泵 询问方案、价格或寻找供应商",
        "离心水泵 询问方案、价格或寻找供应商",
        "工业水泵 询问方案、价格或寻找供应商 -招聘 -二手",
        "工业水泵",
        "离心水泵 询问方案、价格或寻找供应商 -招聘 -二手",
        "离心水泵",
        "工业水泵 比较方案或供应商并准备选型 -招聘 -二手",
        "离心水泵 比较方案或供应商并准备选型 -招聘 -二手",
        "工业水泵 替换现有供应商或系统 -招聘 -二手",
        "离心水泵 替换现有供应商或系统 -招聘 -二手"
      ]
    }
  }
] satisfies { name: string; input: RadarPlanInput; plan: RadarPlan }[];
